DELETE http://localhost:8081/api/product/2
Accept: application/json

###
PUT http://localhost:8081/api/product/2
Content-Type: application/json

{
  "name": "YPK1",
  "type": "AS"
}

###
POST http://localhost:8081/api/product
Content-Type: application/json

{
  "name": "aa",
  "type": "aa"

}

###
GET http://localhost:8081/api/product
Accept: application/json

###
GET http://localhost:8081/api/product/tes
Accept: application/json

###
