POST http://localhost:8082/api/person/booking
Content-Type: application/json

{
  "person": {
    "name": "r7",
    "destination": "jkt",
    "age": 25,
    "active": true,
    "travelDate": "14-12-2020",
    "pickupTime": "12.30 PM",
    "arrivalTime": "2.00 PM",
    "email": "abc@gmail",
    "fare": 10000.0,
    "source": "pku"
  },
  "paymentInfo": {
    "accountNo": "acc1",
    "cardType": "Debit"
  }
}

###
GET http://localhost:8082/api/person/findByNamev2?name=r4
Accept: application/json

###
GET http://localhost:8082/api/person/findByName?name=r7
Accept: application/json

###
GET http://localhost:8082/api/person/findActiveUsersWithAgeGreaterThan?age=10
Accept: application/json

###
POST http://localhost:8082/api/person
Content-Type: application/json

{
  "name": "r8",
  "destination": "jkt",
  "age": 25,
  "active": true,
  "travelDate": "14-12-2020",
  "pickupTime": "12.30 PM",
  "arrivalTime": "2.00 PM",
  "email": "abc@gmail",
  "fare": 12000.0,
  "source": "pku"
}

###
GET http://localhost:8082/api/person
Accept: application/json

###
GET http://localhost:8082/api/person/2
Accept: application/json

###
GET http://localhost:8082/api/person/tes
Accept: application/json

###
GET http://localhost:8082/api/person/get
Accept: application/json

###
